### ISSUE TITLE
where is frida-gadget config

### ISSUE THREAD

**Issue by unknown-error-601** [VitalikObject/brawl-stars-server#10]
what and where is the frida-gadget config? how do I edit the IP address?

**Comment by ghost** [comment]
You should unpack this apk (pre-made client)###  https://drive.google.com/file/d/14dR35AJbVfFN83kbMb6GLBHyomHE0hWj/view
and go to lib/armeabi-v7a, then edit libgg.config.so file. When you edited it, save and 
compress to zip archive your unpacked apk, rename extension to .apk and sign it (with ZipSigner on Android, or Easy APK Tool on windows), then install. This will be work.

**Comment by KitenokGene** [comment]
lib/armeabi-v7a/libgg.config.so
