### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by cursedsherryl** [VitalikObject/brawl-stars-server#7]
when I attempt to use the server, I run the script just fine and it connects, but when I connect to it on my phone it gets to the TOS confirm thing, stutters for a bit, and then freezes and crashes. on the computer it looks like this

[INFO] Server started! Ip: 0.0.0.0, Port: 9339
[INFO] New connection! Ip: [insert my ip]
[INFO] Received packet! Id: 18101
[INFO] Message LoginOk has been sent.
[INFO] Message OwnHomeData has been sent.
[INFO] Packet don't handled! Id: 10111
[INFO] Received packet! Id: 10110
[INFO] Economy {"subType":"InAppPurchase","product":"productsreceived","productDetails":"","Revenue":"0","PCChange":"0","Transaction id":"","Error code":"0","Store country":"EN","Count":"0"}
[INFO] Ip: [insert my ip] disconnected!

note: my texts.csv and cards.csv are modified, if that has anything to do with it

**Comment by okyk738** [comment]
What is your client version which you attempting to connect with server (sorry for bad english)

**Comment by VitalikObject** [comment]
You use python3?

**Comment by okyk738** [comment]
Hmm.. what is the message id 10111?

**Comment by cursedsherryl** [comment]
I do use Python 3, and the version I use is v26

**Comment by okyk738** [comment]
> note: my texts.csv and cards.csv are modified, if that has anything to do with it

You are tried to use the server without changing this files?

**Comment by JackRichardBusiness** [comment]
I'm getting the same error, nothing modified.
**"Packet don't handled!"** on packet IDs 10111 and 14366, then crashes.

**Comment by okyk738** [comment]
Hmm, ok.. I can attempt to modify premade client, maybe i can run the server without this problem.
